/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */

import * as Context from './src/graphql/context/index';

declare global {
  interface NexusGenCustomOutputProperties<TypeName extends string> {
    crud: NexusPrisma<TypeName, 'crud'>;
    model: NexusPrisma<TypeName, 'model'>;
  }
}

declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {}

export interface NexusGenEnums {}

export interface NexusGenScalars {
  String: string;
  Int: number;
  Float: number;
  Boolean: boolean;
  ID: string;
}

export interface NexusGenRootTypes {
  JwtAuthUser: {
    // root type
    token: string; // String!
    user: NexusGenRootTypes['User']; // User!
  };
  Mutation: {};
  Query: {};
  User: {
    // root type
    email: string; // String!
    id: number; // Int!
    name: string; // String!
    password: string; // String!
  };
}

export interface NexusGenAllTypes extends NexusGenRootTypes {
  String: NexusGenScalars['String'];
  Int: NexusGenScalars['Int'];
  Float: NexusGenScalars['Float'];
  Boolean: NexusGenScalars['Boolean'];
  ID: NexusGenScalars['ID'];
}

export interface NexusGenFieldTypes {
  JwtAuthUser: {
    // field return type
    token: string; // String!
    user: NexusGenRootTypes['User']; // User!
  };
  Mutation: {
    // field return type
    deleteUserById: NexusGenRootTypes['User']; // User!
    login: NexusGenRootTypes['JwtAuthUser']; // JwtAuthUser!
    signup: NexusGenRootTypes['User']; // User!
    updateUserById: NexusGenRootTypes['User']; // User!
  };
  Query: {
    // field return type
    allUsers: NexusGenRootTypes['User'][]; // [User!]!
    getMe: NexusGenRootTypes['User']; // User!
    userById: NexusGenRootTypes['User']; // User!
  };
  User: {
    // field return type
    email: string; // String!
    id: number; // Int!
    name: string; // String!
    password: string; // String!
  };
}

export interface NexusGenArgTypes {
  Mutation: {
    deleteUserById: {
      // args
      id?: number | null; // Int
    };
    login: {
      // args
      email?: string | null; // String
      password?: string | null; // String
    };
    signup: {
      // args
      email?: string | null; // String
      name?: string | null; // String
      password?: string | null; // String
    };
    updateUserById: {
      // args
      id?: number | null; // Int
      name?: string | null; // String
    };
  };
  Query: {
    userById: {
      // args
      id?: number | null; // Int
    };
  };
}

export interface NexusGenAbstractResolveReturnTypes {}

export interface NexusGenInheritedFields {}

export type NexusGenObjectNames = 'JwtAuthUser' | 'Mutation' | 'Query' | 'User';

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = 'Boolean' | 'Float' | 'ID' | 'Int' | 'String';

export type NexusGenUnionNames = never;

export interface NexusGenTypes {
  context: Context.Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  allTypes: NexusGenAllTypes;
  inheritedFields: NexusGenInheritedFields;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes:
    | NexusGenTypes['inputNames']
    | NexusGenTypes['enumNames']
    | NexusGenTypes['scalarNames'];
  allOutputTypes:
    | NexusGenTypes['objectNames']
    | NexusGenTypes['enumNames']
    | NexusGenTypes['unionNames']
    | NexusGenTypes['interfaceNames']
    | NexusGenTypes['scalarNames'];
  allNamedTypes:
    | NexusGenTypes['allInputTypes']
    | NexusGenTypes['allOutputTypes'];
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractResolveReturn: NexusGenAbstractResolveReturnTypes;
}

declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {}
  interface NexusGenPluginFieldConfig<
    TypeName extends string,
    FieldName extends string
  > {}
  interface NexusGenPluginSchemaConfig {}
}
